GET localhost:9084/login
Authorization: Digest username password

> {%
    client.global.set("my_cookie", response.headers.valuesOf("Set-Cookie")[0]);
%}
###

GET localhost:9084/welcome
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE4NDgzMjY3MDAsImlhdCI6MTY5MDU0MTk0MCwidXNlciI6IkpvaG4iLCAibGV2ZWwiOiJiYXNpYyJ9.KxowXpGpef8uy97Hyqv2MoGiNcsc5G81Z3LWL_F0I6Y
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE4ODM0MTI4MDksImlhdCI6MTcyNTYyODA0OSwidXNlciI6IkpvaG4iLCAibGV2ZWwiOiJiYXNpYyJ9.PLsD9WCCpzl_mIBbFtKFQkDa87ZhGHAV4NN84l5f6Kk
