### Testing CORS + CSRF
GET localhost:9000/generateCSRF
Origin: localhost

> {%
client.global.set("csrf_token", response.cookie.x-csrf-token);
%}

### Testing CORS + CSRF
POST localhost:9000/validateCSRF
Origin: localhost
Authorization: Basic gunther cc
x-csrf-token: {{csrf_token}}
Cookie: x-csrf-token={{csrf_token}}

### Testing basic auth
GET http://localhost:9000/secret/owls
Authorization: Basic gunther cc


### Testing Websocket
WEBSOCKET ws://localhost:9000/ws

"Hallo Welt"
===
"Wunderbar"
===
"Noch eins"
=== wait-for-server