name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: sbt
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - uses: japgolly/setup-scalajs@v1
    - name: Run tests
      run: sbt test
