name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up JDK 27
        uses: actions/setup-java@v6
        with:
          java-version: '27'
          distribution: 'temurin'
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Install jsdom
        run: npm install jsdom
      - name: Run tests
        run: sbt testFull
