name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: sbt
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: japgolly/setup-scalajs@v1
    - name: Run tests
      run: sbt test
  check:
    runs-on: ubuntu-latest
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: zulu@
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: japgolly/setup-scalajs@v1
      - run: sbt test
