name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: sbt test
  check:
    runs-on: ubuntu-latest
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: zulu@1.17.0-0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: japgolly/setup-scalajs@v1
      - run: sbt test
