name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up GraalVM for JDK 23
      uses: actions/setup-java@v5
      with:
        java-version: 23
        distribution: graalvm
        cache: sbt
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - uses: japgolly/setup-scalajs@v1
    - name: Run tests
      run: sbt test
